version: '3.8'

services:
  app-viewer3d:
    build: .
    # Sincroniza a porta 7860 do seu PC com a 7860 do contêiner
    ports:
      - "7860:7860"
    # Sincroniza seus arquivos locais com o contêiner em tempo real.
    # Assim, se você mudar um código no VSCode, não precisa remontar o Docker!
    volumes:
      - .:/app